kafka {
  bootstrap.servers = "node1:9092"
  topic.user-behavior = "user_behavior"
  topic.content-metadata = "content_metadata"
  topic.user-register = "user_register"
  acks = "1"
  retries = 3
  batch.size = 16384
  linger.ms = 5
}

producer {
  users.count = 10000
  contents.music.count = 5000
  contents.video.count = 3000
  events.per-second = 100
  duration.minutes = 60
}
